config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', include('register.urls')),
    path('staff/', include('staff.urls')),
    path('user/', include('user.urls')),
    path('accounts/', include('accounts.urls')),
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'
urlpatterns = [
    path('equip_add/', views.EqAdd.as_view(), name='equip_add'),
    path('equip_update/<int:pk>', views.EqUpdate.as_view(), name='equip_update'),
    path('equip_delete/<int:pk>', views.EqDelete.as_view(), name='equip_delete'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('user_add/', views.UserAdd.as_view(), name='user_add'),
    path('user_update/<int:pk>', views.UserUpdate.as_view(), name='user_update'),
    path('user_delete/<int:pk>', views.UserDelete.as_view(), name='user_delete'),

]

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'
urlpatterns = [
    path('', views.HomeView.as_view(), name='staff_page'),
    path('equip_list', views.EquipListView.as_view(), name='equip_list'),
    path('loan/<int:pk>/', views.loan, name='loan'),
    path('return_eq/<int:pk>/', views.return_eq, name='return_eq'),
    path('user_list', views.UserListView.as_view(), name='user_list'),

]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('', views.HomeView.as_view(), name='user_page'),
    path('equip_list', views.EquipListView.as_view(), name='equip_list'),
   
]

register/models.py
import datetime
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone


class CustomUserManager(UserManager):
    """ユーザーマネージャー"""
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル."""

    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    
    DEPARTMENT_CHOICES = [
        ("営業", '営業部'),
        ("経理", '経理部'),
        ("人事", '人事部'),
        ("IT", 'IT部'),
    ]
    department = models.CharField(
        _('部署'),
        max_length=5,
        choices=DEPARTMENT_CHOICES,
        default="営業部",
    )
        
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = CustomUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """Return the first_name plus the last_name, with a space in
        between."""
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)


class Equipment(models.Model):
    # 備品名称
    name = models.CharField(verbose_name='備品名称', max_length=20, default='')
    # 備品カテゴリー
    EQIPMENT_CHOICES = [
        ("PC", 'PC'),
        ("カメラ", 'カメラ'),
        ("プロジェクター", 'プロジェクター'),
        ("その他", 'その他'),
    ]
    category = models.CharField(
        verbose_name='カテゴリー',
        max_length=20,
        choices=EQIPMENT_CHOICES,
        default="PC",
    )    
    # 購入費用
    price = models.IntegerField(verbose_name='購入費用', default=0)
    # 貸出中
    loaned_out = models.BooleanField(
        default=False,
        help_text=_(
            'if True, being loaned out'),
    )
    # 現在の所持者
    belong_to = models.ForeignKey(User, verbose_name='所持者', on_delete=models.PROTECT, null=True)
    # 返却日
    return_date = models.DateTimeField('return deadline', blank=True, null=True,)
    # 概要
    comment = models.TextField(verbose_name='概要', null=True, blank=True)

    def __str__(self):
        return self.name

    # 返却日の一週間前を知らせる
    def return_day_comming(self):
        return timezone.now() <= self.return_date - datetime.timedelta(days=7)            

class Loan_log(models.Model):
    # 備品
    equipment = models.ForeignKey(Equipment, verbose_name='備品', on_delete=models.PROTECT, null=True)
    # 所有者
    belong_to = models.ForeignKey(User, verbose_name='所持者', on_delete=models.PROTECT, null=True)
    # 貸出日
    loan_date = models.DateTimeField('start loan date', blank=True, null=True,)
    
    def __str__(self):
        return 'pk ' + str(self.pk) + self.equipment.name + str(self.loan_date) 

class Return_log(models.Model):
    # 備品
    equipment = models.ForeignKey(Equipment, verbose_name='備品', on_delete=models.PROTECT, null=True)
    # 所有者
    belong_to = models.ForeignKey(User, verbose_name='所持者', on_delete=models.PROTECT, null=True)
    # 返却日
    return_date = models.DateTimeField('return date', blank=True, null=True,)
    
    def __str__(self):
        return  'pk ' + str(self.pk) + self.equipment.name + str(self.return_date)

register/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm

# 一般ユーザー用　サインアップ
class SignupForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'department',)

# スタッフ用　サインアップ
class UserAddForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name','email', 'department', 'is_staff',)

register/views.py
from django.contrib.auth import login
from django.shortcuts import render,redirect
from .models import User, Equipment
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponseRedirect
from .forms import UserAddForm, SignupForm

# 備品追加
class EqAdd(CreateView):
    template_name = 'register/equip_add.html'
    model = Equipment
    fields = ['name', 'category',  'price', 'comment']

    def get_success_url(self):
        return reverse('register:equip_add')

# 備品情報更新
class EqUpdate(UpdateView):
    template_name = 'register/equip_update.html'
    model = Equipment
    fields = ['name', 'category',  'price', 'comment']

    def get_success_url(self):
 
        return reverse('staff:equip_list')

# 備品詳細
class EqDetail(DetailView):
    template_name = 'register/eq_detail.html'
    model = Equipment

# 備品削除
class EqDelete(DeleteView):
    template_name = 'register/equipment_confirm_delete.html'
    model = Equipment
    success_url = reverse_lazy('staff:equip_list')

# ユーザー作成
class SignupView(CreateView):
    form_class = SignupForm
    template_name = "register/user_signup.html" 
    success_url = reverse_lazy('accounts:login')

    def form_valid(self, form):
        user = form.save() # formの情報を保存
        return redirect('accounts:login') # リダイレクト

# スタッフ用ユーザー追加　is_staffをTrueにできる。
class UserAdd(CreateView):
    form_class = UserAddForm
    template_name = 'register/user_add.html'

    def form_valid(self, form):
        user = form.save()
        return redirect('staff:staff_page')
 
# ユーザー情報更新
class UserUpdate(UpdateView):
    template_name = 'register/user_update.html'
    model = User
    fields = ['first_name', 'last_name',  'email', 'department', ]

    def get_success_url(self):
        return reverse('staff:user_list')

# ユーザー削除
class UserDelete(DeleteView):
    template_name = 'register/user_confirm_delete.html'
    model = User
    success_url = reverse_lazy('staff:user_list')

register/templates/register/equip_add.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block title %}備品追加ページ{% endblock %}

{% block content %}

<div class='container'>

  <div class="text-danger">
    {{form.non_field_errors}}
  </div>

  <form method="POST">{% csrf_token %}
    {% bootstrap_form form %}
    
    <button class="btn btn-success" type='submit' >備品を登録する</button>
  </form>
</div>

{% endblock %}

register/templates/register/equip_update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block title %}備品追加ページ{% endblock %}

{% block content %}

<div class='container'>
    <h2>備品id {{equipment.pk}} {{equipment.name}} 編集画面</h2>

    {% if not equipment.belong_to %}
    <a href="{% url 'staff:loan' equipment.pk %}" 　type='button' class='btn btn-success my-2'>貸出画面に移動</a>
    {% else %}
    <a href="{% url 'staff:return_eq' equipment.pk %}" 　type='button' class='btn btn-success my-2'>返却</a>

    {% endif %}


    <div class="text-danger">
        {{form.non_field_errors}}
    </div>

    <form method="POST">{% csrf_token %}
        {% bootstrap_form form %}
        <!-- モーダルボタン -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
            適用
        </button>

        <!-- モーダル -->
        <div class="modal" id="myModal">
            <div class="modal-dialog">
                <div class="modal-content">

                    <!-- Modal header -->
                    <div class="modal-header">
                        <h4 class="modal-title">確認</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>

                    <!-- Modal body -->
                    <div class="modal-body">
                        備品登録の情報を変更しますか？
                    </div>

                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <button type='submit' class="btn btn-primary">変更</button>
                        <button type="button" class="btn btn-primary" data-dismiss="modal">閉じる</button>

                    </div>

                </div>
            </div>
        </div>
    </form>
</div>

<div class="container d-flex justify-content-center">
    <form method="POST">{% csrf_token %}
        <!-- モーダルボタン -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModa2">
            この備品を削除
        </button>

        <!-- データ削除確認モーダル -->
        <div class="modal" id="myModa2">
            <div class="modal-dialog">
                <div class="modal-content">

                    <!-- Modal header -->
                    <div class="modal-header">
                        <h4 class="modal-title">確認</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>

                    <!-- Modal body -->
                    <div class="modal-body">
                        備品情報を削除しますか？
                    </div>

                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <!-- <a class="btn btn-success" href="{% url 'register:user_update' user.pk %}"></a> -->
                        <a class="btn btn-danger" href="{% url 'register:equip_delete' equipment.pk %} ">削除する</a>
                        <button type="button" class="btn btn-primary" data-dismiss="modal">閉じる</button>

                    </div>

                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

register/templates/register/equipment_confirm_delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block title %}備品情報削除{% endblock %}

{% block content %}

<div class="container">
    <h1>備品情報　削除確認画面</h1>
    <form method="post">
        {% csrf_token %}
        <p>備品ID{{ equipment.pk }}/　{{equipment.name}}をデータベースから削除しますか？</p>
        <input type="submit" value="削除する">
    </form>
    </body>
</div>

{% endblock %}

register/templates/register/staff_add.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block title %}スタッフ追加ページ{% endblock %}

{% block content %}

<div class='container'>
<h4 class="mb-3">ユーザー追加画面</h4>
<p>スタッフを追加する場合はスタッフ権限にチェックをいれてください</p>
  <div class="text-danger">
    {{form.non_field_errors}}
  </div>

  <form method="POST">{% csrf_token %}
    {% bootstrap_form form %}
    
    <button type='submit' class="btn-success" >ユーザーを追加する</button>
  </form>
</div>

{% endblock %}

register/templates/register/user_add.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block title %}スタッフ追加ページ{% endblock %}

{% block content %}

<div class='container'>
<h4 class="mb-3">ユーザー追加画面</h4>
<p>スタッフを追加する場合はスタッフ権限にチェックをいれてください</p>
  <div class="text-danger">
    {{form.non_field_errors}}
  </div>

  <form method="POST">{% csrf_token %}
    {% bootstrap_form form %}
    
    <button type='submit' class="btn-success" >ユーザーを追加する</button>
  </form>
</div>

{% endblock %}

register/templates/register/user_confirm_delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block title %}ユーザー情報削除{% endblock %}

{% block content %}

<div class="container">
    <h1>ユーザー情報 削除確認画面</h1>
    <form method="post">
        {% csrf_token %}
        <p>ユーザーID{{ user.pk }}/　{{ user.first_name}} {{ user.last_name }}をデータベースから削除しますか？</p>
        <input type="submit" value="削除する">
    </form>
    </body>
</div>

{% endblock %}

register/templates/register/user_signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block title %}サインアップページ{% endblock %}

{% block content %}

<div class='container'>
<h4 class="mb-3">サインアップ画面</h4>
  <div class="text-danger">
    {{form.non_field_errors}}
  </div>

  <form method="POST">{% csrf_token %}
    {% bootstrap_form form %}
    
    <button type='submit' class="btn-success" >ユーザー登録する</button>
  </form>
</div>

{% endblock %}

register/templates/register/user_update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block title %}ユーザー情報編集{% endblock %}

{% block content %}

<div class='container'>
    <h2>ユーザーid {{user.pk}} {{user.first_name}} {{user.last_name}} 編集画面</h2>
    <p>＊ユーザーのパスワードはこの画面では変更出来ません</p>

    <div class="text-danger">
        {{form.non_field_errors}}
    </div>

    <form method="POST">{% csrf_token %}
        {% bootstrap_form form %}
        <!-- モーダルボタン -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
            変更する
        </button>

        <!-- モーダル -->
        <div class="modal" id="myModal">
            <div class="modal-dialog">
                <div class="modal-content">

                    <!-- Modal header -->
                    <div class="modal-header">
                        <h4 class="modal-title">確認</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>

                    <!-- Modal body -->
                    <div class="modal-body">
                        ユーザー登録の情報を変更しますか？
                    </div>

                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <button type='submit' class="btn btn-primary">変更</button>
                        <button type="button" class="btn btn-primary" data-dismiss="modal">閉じる</button>

                    </div>

                </div>
            </div>
        </div>
    </form>
</div>
<div class="container d-flex justify-content-center">
    <form method="POST">{% csrf_token %}
        <!-- モーダルボタン -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModa2">
            このユーザーを削除
        </button>

        <!-- モーダル -->
        <div class="modal" id="myModa2">
            <div class="modal-dialog">
                <div class="modal-content">

                    <!-- Modal header -->
                    <div class="modal-header">
                        <h4 class="modal-title">確認</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>

                    <!-- Modal body -->
                    <div class="modal-body">
                        ユーザー情報を削除しますか？
                    </div>

                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <!-- <a class="btn btn-success" href="{% url 'register:user_update' user.pk %}"></a> -->
                        <a class="btn btn-danger" href="{% url 'register:user_delete' user.pk %} " >削除する</a>
                        <button type="button" class="btn btn-primary" data-dismiss="modal">閉じる</button>

                    </div>

                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}