config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', include('register.urls')),
    path('staff/', include('staff.urls')),
    path('user/', include('user.urls')),
    path('accounts/', include('accounts.urls')),
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'
urlpatterns = [
    path('equip_add/', views.EqAdd.as_view(), name='equip_add'),
    path('equip_update/<int:pk>', views.EqUpdate.as_view(), name='equip_update'),
    path('equip_delete/<int:pk>', views.EqDelete.as_view(), name='equip_delete'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('user_add/', views.UserAdd.as_view(), name='user_add'),
    path('user_update/<int:pk>', views.UserUpdate.as_view(), name='user_update'),
    path('user_delete/<int:pk>', views.UserDelete.as_view(), name='user_delete'),

]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('', views.HomeView.as_view(), name='user_page'),
    path('equip_list', views.EquipListView.as_view(), name='equip_list'),
   
]

user/models.py
from django.db import models

# Create your models here.

user/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from register.models import User, Equipment, Loan_log, Return_log
from datetime import date, timedelta 


# Create your views here.
class HomeView(generic.TemplateView):
    template_name = 'user/home.html'


class EquipListView(generic.TemplateView):
    template_name = 'user/equip_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['equip_list'] = Equipment.objects.all()
        return context

user/templates/user/equip_list.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block title %}備品検索ページ{% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md">
            <div class="form-group">
                <label for="search_num">備品ID</label>
                <input type="text" class="form-control" id="search_num">
            </div>
        </div>
        <dif class="col-md">
            <div class="form-group">
                <label for="search_category">カテゴリー:</label>
                <select class="form-control" id="search_category">
                    <option></option>
                    <option>PC</option>
                    <option>カメラ</option>
                    <option>プロジェクター</option>
                    <option>その他</option>
                </select>
            </div>
        </dif>
        <div class="col-md">
            <div class="form-group">
                <label for="search_category">在庫</label>
                <select class="form-control" id="search_loaned">
                    <option></option>
                    <option></option>
                    <option>あり</option>
                    <option>貸出中</option>
                </select>
            </div>
        </div>
    </div>
    <input type="button" value="絞り込む" id="button">
    <input type="button" value="すべて表示" id="button2">

    <table id='result' class="table table-striped">
        <thead>
            <tr>
                <th>備品ID</th>
                <th>名前</th>
                <th>カテゴリー</th>
                <th>購入費用</th>
                <th>在庫</th>
                <th>返却予定日</th>
            </tr>
        </thead>
        <tbody>
            {% for equip in equip_list %}
            <tr>
                <td>{{ equip.id }}</td>
                <td>{{ equip.name }}</td>
                <td>{{ equip.category }}</td>
                <td>{{ equip.price }} 円</td>
                {% if equip.belong_to %}
                <td>貸出中</td>
                {% else %}
                <td>あり</td>
                {% endif %}
                <td>{{ equip.return_date }} </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

<!-- ｊｓファイル読み込み -->
{% block extra_js %}
<script src="{% static 'staff/equip_list.js'%} "></script>
{% endblock%}

user/templates/user/home.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block title %}スタッフページ{% endblock %}

{% block content %}

<div class='container my-3'>
    <div class="row">
        <div class="col-md">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">ユーザー情報変更</h4>
                    <p class="card-text">パスワードの変更は出来ません</p>
                    <a href="{% url 'register:user_update' request.user.pk %} " class="btn btn-primary">備品登録画面に移動</a>
                </div>
            </div>
        </div>
        <div class="col-md">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">備品検索</h4>
                    <p class="card-text">備品情報の検索</p>
                    <a href="{% url 'user:equip_list' %} " class="btn btn-primary">備品検索画面に移動</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}