accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.RedirectView.as_view(), name='show_home'),
    path('login/', views.MyLoginView.as_view(), name="login"),
    path('logout/', views.MyLogoutView.as_view(), name="logout"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', include('register.urls')),
    path('staff/', include('staff.urls')),
    path('user/', include('user.urls')),
    path('accounts/', include('accounts.urls')),
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'
urlpatterns = [
    path('equip_add/', views.EqAdd.as_view(), name='equip_add'),
    path('equip_update/<int:pk>', views.EqUpdate.as_view(), name='equip_update'),
    path('equip_delete/<int:pk>', views.EqDelete.as_view(), name='equip_delete'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('user_add/', views.UserAdd.as_view(), name='user_add'),
    path('user_update/<int:pk>', views.UserUpdate.as_view(), name='user_update'),
    path('user_delete/<int:pk>', views.UserDelete.as_view(), name='user_delete'),

]

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'
urlpatterns = [
    path('', views.HomeView.as_view(), name='staff_page'),
    path('equip_list', views.EquipListView.as_view(), name='equip_list'),
    path('loan/<int:pk>/', views.loan, name='loan'),
    path('return_eq/<int:pk>/', views.return_eq, name='return_eq'),
    path('user_list', views.UserListView.as_view(), name='user_list'),

]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('', views.HomeView.as_view(), name='user_page'),
    path('equip_list', views.EquipListView.as_view(), name='equip_list'),
   
]

templates/base.html
<!doctype html>
{% load bootstrap4 %}
{% bootstrap_css%}
{% bootstrap_javascript jquery='True'%}
<html lang="ja">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    {#--- css --- #}
    {% block extra_css %}{% endblock%}
</head>

<body>
    <nav class="navbar navbar-expand-sm bg-info navbar-dark mb-3">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="navbar-brand" href="{% url 'accounts:show_home' %} ">備品管理システム</a>
            </li>

            <li class='nav-item'>
                <a class="nav-link text-white" href="{% url 'accounts:logout' %} ">ログアウト</a>
            </li>
            <li class='nav-item'>
                <a class="nav-link text-white" href="{% url 'register:signup' %} ">サインアップ</a>
            </li>
            <li class='nav-item'>
                <a class="nav-link text-white" href="{% url 'staff:staff_page' %} ">スタッフページ</a>
            </li>
        </ul>

    </nav>


    {% block content %}{% endblock%}

    {#--- js --- #}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q 8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="an onymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.mi n.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86d IHNDz0W1" crossorigin="anonymous">
    </script>

    {% block extra_js %}{% endblock%}
</body>

</html>