config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', include('register.urls')),
    path('staff/', include('staff.urls')),
    path('user/', include('user.urls')),
    path('accounts/', include('accounts.urls')),
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'
urlpatterns = [
    path('equip_add/', views.EqAdd.as_view(), name='equip_add'),
    path('equip_update/<int:pk>', views.EqUpdate.as_view(), name='equip_update'),
    path('equip_delete/<int:pk>', views.EqDelete.as_view(), name='equip_delete'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('user_add/', views.UserAdd.as_view(), name='user_add'),
    path('user_update/<int:pk>', views.UserUpdate.as_view(), name='user_update'),
    path('user_delete/<int:pk>', views.UserDelete.as_view(), name='user_delete'),

]

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'
urlpatterns = [
    path('', views.HomeView.as_view(), name='staff_page'),
    path('equip_list', views.EquipListView.as_view(), name='equip_list'),
    path('loan/<int:pk>/', views.loan, name='loan'),
    path('return_eq/<int:pk>/', views.return_eq, name='return_eq'),
    path('user_list', views.UserListView.as_view(), name='user_list'),

]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('', views.HomeView.as_view(), name='user_page'),
    path('equip_list', views.EquipListView.as_view(), name='equip_list'),
   
]

staff/models.py
from django.db import models

# Create your models here.

staff/forms.py
from django import forms
from django.core.exceptions import ObjectDoesNotExist
from register.models import User

class LoanForm(forms.Form):
    # 貸出用フォーム
    userID = forms.IntegerField(label='ユーザーID', initial=1)
    loan_day = forms.IntegerField(label='貸出日数')

    def clean_loan_day(self):
        loan_day = self.cleaned_data['loan_day']
        if loan_day < 1 :
            raise forms.ValidationError(
        '貸出日数は１日以上です'
        )
        return loan_day

    def clean(self):
        userID = self.cleaned_data.get('userID')
        try:
            userID = User.objects.get(id=userID)
            print('heraaaaaaaaaa')
        except ObjectDoesNotExist:
            print('validation error')
            raise forms.ValidationError('そのユーザーIDは存在しません')

staff/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from register.models import User, Equipment, Loan_log, Return_log
from .forms import LoanForm
from datetime import date, timedelta 


class HomeView(generic.TemplateView):
    template_name = 'staff/home.html'


class EquipListView(generic.TemplateView):
    template_name = 'staff/equip_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['equip_list'] = Equipment.objects.all()
        return context

def loan(request, pk):
    if request.method == 'POST':
        form = LoanForm(request.POST)
        if form.is_valid():
            loan_date = timedelta(form.cleaned_data.get('loan_day'))
            user = User.objects.get(id=form.cleaned_data.get('userID')) 
            equip = Equipment.objects.get(id=pk)
            equip.belong_to = user
            equip.return_date = loan_date + date.today()
            equip.save()
            l = Loan_log(equipment=equip, belong_to=user, loan_date=date.today() )
            l.save()
            return redirect('staff:equip_list')
        else:
            return render(request, 'staff/loan.html', {'form':form})

    equipment = Equipment.objects.get(pk=pk)
    context = {
        'equipment':equipment,
        'form':LoanForm()
    }
    return render(request, 'staff/loan.html', context)

def return_eq(request, pk):
    equip = Equipment.objects.get(id=pk)
    log = Return_log(equipment=equip, belong_to=equip.belong_to, return_date=date.today())
    log.save()
    equip.belong_to = None
    equip.return_date = None
    equip.save()
    
    return redirect('staff:equip_list')


class UserListView(generic.TemplateView):
    template_name = 'staff/user_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_list'] = User.objects.all()
        return context

staff/templates/staff/equip_list.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block title %}備品検索ページ{% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md">
            <div class="form-group">
                <label for="search_num">備品ID</label>
                <input type="text" class="form-control" id="search_num">
            </div>
        </div>
        <dif class="col-md">
            <div class="form-group">
                <label for="search_category">カテゴリー:</label>
                <select class="form-control" id="search_category">
                    <option></option>
                    <option>PC</option>
                    <option>カメラ</option>
                    <option>プロジェクター</option>
                    <option>その他</option>
                </select>
            </div>
        </dif>
        <div class="col-md">
            <div class="form-group">
                <label for="search_category">在庫</label>
                <select class="form-control" id="search_loaned">
                    <option></option>
                    <option></option>
                    <option>あり</option>
                    <option>貸出中</option>
                </select>
            </div>
        </div>
    </div>
    <input type="button" value="絞り込む" id="button">
    <input type="button" value="すべて表示" id="button2">

    <table id='result' class="table table-striped">
        <thead>
            <tr>
                <th>備品ID</th>
                <th>名前</th>
                <th>カテゴリー</th>
                <th>購入費用</th>
                <th>在庫</th>
                <th>所持者</th>
                <th>返却予定日</th>
                <th>詳細</th>
            </tr>
        </thead>
        <tbody>
            {% for equip in equip_list %}
            <tr>
                <td>{{ equip.id }}</td>
                <td>{{ equip.name }}</td>
                <td>{{ equip.category }}</td>
                <td>{{ equip.price }} 円</td>
                {% if equip.belong_to %}
                <td>貸出中</td>
                {% else %}
                <td>あり</td>
                {% endif %}
                <td>{{ equip.belong_to }}</td>
                <td>{{ equip.return_date }} </td>
                <td><a class="btn btn-success" href="{% url 'register:equip_update' equip.pk %}">詳細</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

<!-- ｊｓファイル読み込み -->
{% block extra_js %}
<script src="{% static 'staff/equip_list.js'%} "></script>
{% endblock%}

staff/templates/staff/home.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block title %}スタッフページ{% endblock %}

{% block content %}

<div class='container my-3'>
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">備品登録</h4>
                    <p class="card-text">新しい備品の登録</p>
                    <a href="{% url 'register:equip_add' %} " class="btn btn-primary">備品登録画面に移動</a>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">備品検索</h4>
                    <p class="card-text">備品情報の検索・編集・返却手続き</p>
                    <a href="{% url 'staff:equip_list' %} " class="btn btn-primary">備品検索画面に移動</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class='container my-5'>
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">ユーザー追加</h4>
                    <p class="card-text">ユーザーとスタッフの追加</p>
                    <a href="{% url 'register:user_add'  %}" class="btn btn-primary">ユーザ-追加画面に移動</a>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">ユーザー情報</h4>
                    <p class="card-text">ユーザ情報の確認・編集</p>
                    <a href="{% url 'staff:user_list'  %}" class="btn btn-primary">ユーザー情報画面に移動</a>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}

staff/templates/staff/loan.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block title %}貸出ページ{% endblock %}

{% block content %}

<div class='container'>
    <h2>備品id {{equipment.pk}} {{equipment.name}}  貸出画面</h2>
   
    <div class="text-danger">
        {{form.non_field_errors}}
    </div>

    <form method="POST">{% csrf_token %}
        {% bootstrap_form form %}
        <button type='submit' class="btn btn-primary">貸出</button>
    </form>    
</div>


{% endblock %}

staff/templates/staff/return_eq.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block title %}返却ページ{% endblock %}

{% block content %}

<div class='container'>
    <h2>備品id {{equipment.pk}} {{equipment.name}}  返却画面</h2>
   
    <div class="text-danger">
        {{form.non_field_errors}}
    </div>

    <form method="POST">{% csrf_token %}
        <button type='submit' class="btn btn-primary">返却</button>
    </form>    
</div>


{% endblock %}

staff/templates/staff/user_list.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block title %}ユーザーリスト{% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md">
            <div class="form-group">
                <label for="search_num">ユーザーID</label>
                <input type="text" class="form-control" id="search_num">
            </div>
        </div>
        <div class="col-md">
            <div class="form-group">
                <label for="search_name">名前</label>
                <input type="text" class="form-control" id="search_name">
            </div>
        </div>
        <div class="col-md">
            <div class="form-group">
                <label for="search_email">Eメール</label>
                <input type="text" class="form-control" id="search_email">
            </div>
        </div>
        <div class="col-md">
            <div class="form-group">
                <label for="search_department">部署</label>
                <select class="form-control" id="search_department">
                    <option></option>
                    <option>営業</option>
                    <option>経理</option>
                    <option>人事</option>
                    <option>IT</option>
                </select>
            </div>
        </div>
    </div>
    <input type="button" value="絞り込む" id="button">
    <input type="button" value="すべて表示" id="button2">
</div>
<div class="container">
    <table id='result' class="table table-striped">
        <thead>
            <tr>
                <th>ユーザーID</th>
                <th>名前</th>
                <th>Eメール</th>
                <th>部署</th>
                <th>詳細</th>

            </tr>
        </thead>
        <tbody>
            {% for user in user_list %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.first_name }} {{user.last_name}}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.department }} </td>
                <td><a class="btn btn-success" href="{% url 'register:user_update' user.pk %}">詳細</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

<!-- ｊｓファイル読み込み -->
{% block extra_js %}
<script src="{% static 'staff/user_list.js'%} "></script>
{% endblock%}